checkpoint:
  log: 1
  model: 100
  test: 1
  val: 1
  verbose: false
data:
  cutoff: 5.0
  dataset_file_name: ethanol_dft.npz
  molecule: ethanol
  random_states: 90
  test_path: false
  test_size: 1000
  train_size: 950
  val_size: 50
general:
  device: cpu
  driver: N/A
  file_type: yml
  me: params.yml
  output:
  - trainings
  - 1
  root: N/A
  run_name: training
hooks:
  vismolvector3d: false
model:
  activation: swish
  aggregration: sum
  cutoff_network: poly
  double_update_latent: false
  layer_norm: false
  max_z: 10
  n_features: 128
  n_interactions: 3
  normalize_atomic: false
  normalize_filter: false
  pre_trained: false
  requires_dr: true
  resolution: 20
  return_latent: true
  shared_interactions: false
  w_at_energy: 1.0
  w_energy: 1.0
  w_f_dir: 1.0
  w_f_mag: 0.0
  w_force: 100.0
  wf_decay: 0.0
training:
  drop_last: true
  dropout: 0.0
  epochs: 5000
  lr: 0.001
  lr_scheduler:
  - plateau
  - 15
  - 30
  - 0.7
  - 1.0e-06
  shuffle: true
  tr_batch_size: 12
  tr_frz_rot: false
  tr_keep_original: true
  tr_rotations: 0
  val_batch_size: 12
  val_frz_rot: false
  val_keep_original: true
  val_rotations: 0
  weight_decay: 0
